### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by ankitnayan12** [onnx/model-zoo#15]
![Screenshot (165)](https://user-images.githubusercontent.com/45805922/71722232-2cabba00-2e4e-11ea-9879-1e0356f0d16e.png)

**Comment by ankitnayan12** [comment]
can you help whats wrong here?

**Comment by lupesko** [comment]
@ankitnayan12 note that this repo is deprecated. 
model-zoo has been merge into [onnx/models](https://github.com/onnx/models).
