### ISSUE TITLE
Top level classifications are a mixture

### ISSUE THREAD

**Issue by simoncorstonoliver** [onnx/model-zoo#9]
The top level classifications on the landing page mix two different things with results that make it difficult to navigate:

1. research domain or application (e.g. NLP, Image classification)
2. model architecture

I would suggest that the top level organization be research application only. Generative models or autoencoders are a low-level implementation thing -- model architectures you can use to solve various problems so put those models under the problem domain.

Also, traditionally ASR and TTS would not be considered NLP (they have entirely different conferences and journals for example).

A possible high level organization might be:

Computer vision / Computer graphics
- Image detection
- Semantic segmentation
- Face detection
- Super resolution
- Style transfer
...

NLP
- NMT
- Language modeling

Speech
- ASR
- TTS (Deep Voice, Wavenet etc)

Vision + NLP
- Visual question answering etc

**Comment by abhinavs95** [comment]
@simoncorstonoliver Thanks for the suggestion. I'll put in these changes in my next PR. 

Just to clarify, are you suggesting to have a two level layout, eg., Vision-> image detection -> models ; NLP -> NMT -> models ... OR have the current one level layout but with modified sections?

**Comment by simoncorstonoliver** [comment]
In my brain it's a two level layout as you describe but for UX it might be best to flatten it. The big thing for me is not to have a heading which is a model architecture.

**Comment by abhinavs95** [comment]
@simoncorstonoliver see [#11](https://github.com/onnx/model-zoo/pull/11), I have made the changes you suggested.

**Comment by abhinavs95** [comment]
Suggested changes have been merged in #11 .. closing
